# admin token secret
apiVersion: v1
kind: Secret
metadata:
  name: kong-admin-token-secret
  namespace: kong-local
data:
  token: SkBqaTE5ODVKQGhu
type: Opaque
---


# postgresql secrets
apiVersion: v1
kind: Secret
metadata:
  name: kong-cp-postgresql
  namespace: kong-local
type: Opaque
data:
  password: QG5HNWxKQGpp
  postgres-password: QG5HNWxKQGpp
# kubectl apply -f kong-postgresql.yaml -n kong-local
---


apiVersion: v1
kind: Secret
metadata:
  name: kong-enterprise-superuser-password
  namespace: kong-local
data:
  password: SkBqaTE5ODVKQGhu
type: Opaque
