# admin token secret
apiVersion: v1
kind: Secret
metadata:
  name: kong-admin-token-secret
  namespace: kong-datamigration
data:
  token: SkBqaTE5ODVKQGhu
type: Opaque
---

apiVersion: v1
kind: Secret
metadata:
  name: kong-enterprise-superuser-password
  namespace: kong-datamigration
data:
  password: SkBqaTE5ODVKQGhu
type: Opaque
